### ISSUE TITLE
pip doesn't respect dependencies

### ISSUE THREAD

**Issue by doctorcolossus** [theJollySin/mazelib#96] opened 2019-07-02 02:05 UTC
There's one more problem I'm facing that you might be able to help with. We're using Travis CI, an automated testing system. If you aren't familiar, Travis CI is a cloud app which - for every commit - creates a fresh virtual machine, installs your requirements, and in our case runs pylint, flake8, and pytest.

Our requirements are installed via "pip install -r requirements.txt", but this is not working for mazelib, and I guess it's because pip tries to install mazelib first, and that fails because neither cython and numpy have been installed yet.

I don't get why it does that, because both dependencies *are* specified in the 'install_requires' of your setup.py... However, my working theory is that this may be because you actually import and use both cython and numpy in the actual setup.py, and maybe setuptools doesn't get as far as parsing 'install_requires', since it can't import the packages specified on the first lines of setup.py. I found [this issue](https://github.com/SciTools/cf-units/pull/108) on another project, which seemed similar. They in turn link to [this](http://docs.cython.org/en/latest/src/userguide/source_files_and_compilation.html#distributing-cython-modules), in cython's docs, which seems to discourage using cython in setup.py at all. I've never messed with cython/cythonize before, beyond just installing it, so I'm not really sure where to go with this.

So far I've tried:
- listing cython and numpy in our project's requirements.txt
  - This fails, as pip tries to install mazelib first, regardless of the ordering.
- creating a requirements.txt in a fork of mazelib
  - no change
- using different combinations of cython and numpy in 'install_requires' and 'setup_requires'

You should be able to replicate this issue by trying to "pip install mazelib" in a fresh virtual environment with no cython or numpy:

```
/tmp $ virtualenv env
Using base prefix '/usr'
New python executable in /tmp/env/bin/python
Installing setuptools, pip, wheel...
done.
/tmp $ source env/bin/activate
(env) /tmp $ pip install mazelib
Collecting mazelib
  Using cached https://files.pythonhosted.org/packages/d2/c4/0a15714c215f154833636511d269fd2ebaa05c3d2c81bd235fe0e13c0173/mazelib-0.8.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-e0xdjx9f/mazelib/setup.py", line 25, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-e0xdjx9f/mazelib/
```

My next idea is just to just edit our script for Travis CI as a workaround. That should get us by for now, so in case a fix for this would require major changes, it is not a super-high priority. But if you can think of a simple fix, it would be awesome. Or if it could be something we're doing wrong on our end, please let me know. Thanks!

**Comment by theJollySin** [comment] 2019-07-02 02:38
That's interesting.  So you can't build the project using Cython unless you already have it installed.  So, build process is to do the `pip install -r requirements.txt` first, so I just never ran into this problem.

I guess I could make the installation happen *without* Cython if it's not installed.  I can't say that I've tested the project without Cython.  I suppose it will work.  But... it would need testing.

**Comment by theJollySin** [comment] 2019-07-02 02:53
Have you tried adding a `setup_requires` to the `setup.py` file?

```python
    setup_requires=[
        'cython>=0.x',
        'numpy',
    ],
```

That's my current guess as a solution.  I will have to try it tomorrow though, because it's getting late and I need to crash.

**Comment by doctorcolossus** [comment] 2019-07-02 07:18
Yep, I tried replacing install_requires with setup_requires, as well as adding them both, and I just double-checked copying & pasting your exact syntax above just to be sure, but alas - the output is always the same as above.

> So, build process is to do the pip install -r requirements.txt first, so I just never ran into this problem.
Yes, exactly. I hadn't either, but yeah, that constraint of this automated build process brought it to light. Normally I would just "pip install" my way right through a problem like that

> I guess I could make the installation happen without Cython if it's not installed. I can't say that I've tested the project without Cython. I suppose it will work. But... it would need testing.
That would work, but obviously it would be more optimal to be able to install Cython. It's just that, for some reason, pip isn't bringing that in.

But [according to the Cython docs](http://docs.cython.org/en/latest/src/userguide/source_files_and_compilation.html#distributing-cython-modules), "It is strongly recommended that you distribute the generated .c files as well as your Cython sources, so that users can install your module without needing to have Cython available. It is also recommended that Cython compilation not be enabled by default in the version you distribute. Even if the user has Cython installed, he/she probably doesn’t want to use it just to install your module. Also, the installed version may not be the same one you used, and may not compile your sources correctly. This simply means that the setup.py file that you ship with will just be a normal distutils file on the generated .c files." They go on to include a couple of examples of recommended setup.py files.

My theory is that if you could get the Cython import out of setup.py, then pip would paradoxically then be able to pull in Cython as a dependency and install it for use inside the actual program. But that might be too complicated to be worthwhile. I don't know enough about Cython to advise.

However, even without the Cython imports, the same problem remains with numpy. If I manually install Cython and then try "pip install ." on a cloned copy in a virtual environment without numpy, I get the exact same error about it:
```
(env) /tmp/mazelib $ pip install .
Processing /tmp/mazelib
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-g3tn804u/setup.py", line 28, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-g3tn804u/
(env) /tmp/mazelib $ pip install cython
Collecting cython
  Using cached https://files.pythonhosted.org/packages/4b/00/91306ef12fb2378a427a0bd876000dc6ab3e4b9255ba6b7b93e2515794c3/Cython-0.29.11-cp37-cp37m-manylinux1_x86_64.whl
Installing collected packages: cython
Successfully installed cython-0.29.11
(env) /tmp/mazelib $ pip install .
Processing /tmp/mazelib
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-mmmoiwso/setup.py", line 31, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-mmmoiwso/
```

**Comment by theJollySin** [comment] 2019-07-02 11:17
@doctorcolossus  That *is* interesting.   I guess packing the C files in the repo would work, though it seems ugly. But okay, fine.

> My theory is that if you could get the Cython import out of setup.py, then pip would paradoxically then be able to pull in Cython as a dependency and install it for use inside the actual program. 

This is exactly the problem though.  Because you *need* Cython in your Python Environment to build and install the code.  Cython isn't just a dependency *inside* the project.  Cython is the tool you are using to compile the code.  It's like saying you want to compile a C program *before* you install GCC.

I can confirm though, with a fresh virtualenv that I need to `pip install` Cython and NumPy before I can `pip install mazelib`.  Both are in the requirements.txt file, which I manually run before installation.  It *is* very strange that `pip install` doesn't honor that order of operations. I can imagine removing the NumPy dependence from the setup.py file.  But that still leaves the fact that `pip install` doesn't seem to allow for real Cython builds through the usual channels. *That* is a little annoying.

Options:

1) I can split the setup.py into two pieces, for if you have Cython installed in your env beforehand or not.  That's easy to do. Though would leave some users (like you) with poorer performance.  And I would have to support two completely different builds.  (This is your "get the Cython dependency out of the setup.py" option.)

2) I can try including the *.c files to see if there is some way that setup.py will magically allow for the user to build the code from source themselves.  I doubt this will fix your problem though.

At the moment, I'm leaning towards option (1), though I am not in love with it.

**Comment by doctorcolossus** [comment] 2019-07-02 23:36
`At the moment, I'm leaning towards option (1), though I am not in love with it.`

Me neither. I feel like there must be a way to get Cython to install as a dependency. Maybe we consult with the Cython and/or pip teams. It seems like somebody must have had this issue before... I will keep thinking about it and let you know if I come up with any new ideas.

**Comment by theJollySin** [comment] 2019-07-03 00:23
@doctorcolossus There is also the issue of the timeline of your project. I could release a version to the Pip repo today with option (1), no Cython. And then we can try to figure out how people are dealing with this issue and do it right tomorrow.

BUT if your project isn't *that* time sensitive, perhaps its best to wait and get it right.  You're totally right though *someone* has solved this problem.

**Comment by theJollySin** [comment] 2019-07-03 00:33
@doctorcolossus Yeah, people are pretty clear there is not PyPI solution to this.  The solution is to have the ability to install without Cython, OR to just install Cython first:

https://github.com/pypa/pip/issues/1958

The opinion in the PyPI community is something like "Cython is not a dependency, you wouldn't expect to build C code before installing GCC".  So far I have not found any real work-arounds.  Is there really no way to tell TravisCI to install Cython first?  That seems like a disadvantage.

**Comment by doctorcolossus** [comment] 2019-07-03 00:58
> There is also the issue of the timeline of your project.

Thanks for taking that into consideration! We are good though. Our deadline for this sprint was a couple of hours ago, and we managed to get everything working fine. :)

>  Is there really no way to tell TravisCI to install Cython first? That seems like a disadvantage.

We can actually configure Travis to run whatever we want, which is exactly what I did as a temporary workaround (by modifying the .travis.yml script to install mazelib's dependencies separately, before our other ones). However, I don't really think we're supposed to change that file though, so it's possible they will come down on us for doing so at some point in the future.

**Comment by doctorcolossus** [comment] 2019-07-03 05:42
I'm not sure if this will be helpful, but I found another package which depends on both Cython and NumPy whose setup.py ran okay in a fresh virtual environment without either dependency preinstalled: [Ta-Lib](https://github.com/mrjbq7/ta-lib), the Python wrapper for the C technical analysis library of the same name. [In their setup.py](https://github.com/mrjbq7/ta-lib/blob/master/setup.py), they seem to handle Cython like this:

```
try:
    from Cython.Distutils import build_ext
    has_cython = True
except ImportError:
    has_cython = False

if has_cython:
cmdclass['build_ext'] = build_ext
```

pip-installing it did result in the building of an egg containing a file with an .so extension which appears to be a compiled binary, judging from the output of the Linux file command: "ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked".

I still do not understand much about Cython, but I'm hoping this might point you in the right direction or at least serve as inspiration. :)

**Comment by theJollySin** [comment] 2019-07-03 11:14
@doctorcolossus Yup! It looks like their solution was to just install the Python-only version on the code if Cython isn't available.  That's our option (1).  I can give that a whirl tonight, no problem.  And thanks for all your research.

**Comment by theJollySin** [comment] 2019-07-05 18:40
Okay, this was a multi-fold problem:

1) PyPI doesn't support Cython compiling in every way I would like. Oh well.
2) I was importing Cython and NumPy in setup.py, and PyPI does support that.  Oh well.
3) I was accidentally importing NumPy in setup.py, when trying to import `mazelib.__version__`.

But these issues are now fixed.  If you do:

    pip install mazelib==0.8.4

(or any version newer than that in the future), the import problems in PyPI will be gone.

Cheers!

**Closed by theJollySin** 2019-07-05 18:40 UTC

**Comment by doctorcolossus** [comment] 2019-07-06 20:39
Great, thank you!
Confirmed working. :)
